name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: client/tasksManager
        run: npm install

      - name: Run linter (if exists)
        working-directory: client/taskManager
        run: npm run lint || echo "No linter defined"

      - name: Run tests (if exists)
        working-directory: client/taskManager
        run: npm test || echo "No tests defined"

      - name: Build project
        working-directory: client/taskManager
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/taskManager/dist
